export const types = {
  SET_INPUT_VALUE: 'SET_INPUT_VALUE',
  START_REQUEST: 'START_REQUEST',
  PROGRESS_VALUE: 'PROGRESS_VALUE',
  REQUEST_SUCCESSFUL: 'REQUEST_SUCCESSFUL',
  REQUEST_FAILURE: 'REQUEST_FAILURE',
};
