// auth types
export const USER_LOGGED = 'USER_LOGGED';
export const USER_NOT_LOGGED = 'USER_NOT_LOGGED';

export const UPDATE_PROFILE = 'UPDATE_PROFILE';

// rooms types
export const UPDATE_AVAIABLE_ROOMS = 'UPDATE_AVAIABLE_ROOMS';
export const JOIN_ROOM_WITHOUT_PASS = 'JOIN_ROOM_WITHOUT_PASS';
export const UPDATE_ACTIVE_ROOM = 'UPDATE_ACTIVE_ROOM';
export const DELETE_ACTIVE_ROOM_DATA = 'DELETE_ACTIVE_ROOM_DATA';
