export interface WordsObject {
  [key: string]: string[];
}

export const soloTrainingWords = {
  a: [],
  i: [],
  e: [],
  z: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  o: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  n: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  r: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  y: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  s: ['za', 'aza', 'aeza', 'zezi', 'i', 'ea', 'ezi', 'zie', 'zi'],
  w: [],
  c: [],
  k: [],
  t: [],
  p: [],
  d: [],
  m: [],
  u: [],
  l: [],
  ł: [],
  ć: [],
  j: [],
  b: [],
  g: [],
  ś: [],
  ę: [],
  h: [],
  ą: [],
  ó: [],
  ż: [],
  f: [],
  ń: [],
  ź: [],
  ',': [],
  '.': [],
  '?': [],
  '!': [],
};
